const phrases = [
    "Roll for beta.",
    "The prophecy foretold dry sandstone.",
    "Critical send chance increased.",
    "Your next quest starts at the trailhead.",
    "Dragons fear good footwork.",
    "Mana is temporary. Skin is forever.",
    "Side quest: climb everything.",
    "Fast travel unavailable. Hike harder.",
    "+5 Dexterity, +20 Chalk.",
    "The crux was inside us all along.",
    "Saving throws against pump not included.",
    "A wizard never arrives at a wet crag.",
    "Respawn point: the parking lot.",
    "Loot first. Send later.",
    "Every boulder is a mimic until proven otherwise.",
    "Gather your party before approaching the crag.",
    "May the friction be with you.",
    "Winter is coming. Check the forecast.",
    "One does not simply onsight Mordor.",
    "The fellowship needed better beta.",
    "There and back again... with flappers.",
    "Speak friend and pull on.",
    "The mountain has awoken.",
    "Dungeon master of dry conditions.",
    "Dragons prefer overhangs.",
    "Touch rock. Gain XP.",
    "New achievement unlocked: dry weekend.",
    "The sun buff is active.",
    "Rain debuff detected.",
    "Your project arc begins today.",
    "Cragcraft.",
    "Minecraft prepared you for this.",
    "Dig straight up. Climb straight down.",
    "Legendary loot hidden in the guidebook.",
    "The cake is a lie. The beta isn't.",
    "Portal to good conditions located.",
    "Not enough stamina.",
    "You have died of pumped forearms.",
    "Insert chalk to continue.",
    "Loading next adventure...",
    "Warning: contains side quests.",
    "Peak nerd. Peak granite.",
    "The real treasure was the sends.",
    "Every hold tells a story.",
    "Wet rock is the final boss.",
    "Dryness score over 9000.",
    "Choose your class: Trad, Sport, Boulder.",
    "Character build optimized for slabs.",
    "Multiclassing into alpinism.",
    "Patch notes: friction improved.",
    "Buff applied: cloud cover.",
    "Nerf rain.",
    "Touch grass. Then touch rock.",
    "Endgame content unlocked.",
    "The grind never ends.",
    "Crux happens.",
    "May your projects be short and your sends glorious.",
    "Some heroes wear harnesses.",
    "Heroic difficulty enabled.",
    "Raid group assembling at dawn.",
    "Tank the approach, DPS the crux.",
    "Healers can't save your skin.",
    "Aggro acquired by mosquitoes.",
    "Adventure awaits beyond the parking lot.",
    "Follow the yellow chalk road.",
    "Climbers gonna climb.",
    "The boulder chooses the wizard.",
    "Ancient runes reveal perfect conditions.",
    "Here be dragons. And sandstone.",
    "The oracle predicts splitter weather.",
    "Fortune favors the chalked.",
    "Quest accepted.",
    "Another fine day to battle gravity.",
    "Gravity remains overpowered.",
    "The crag remembers.",
    "Climbers of the round crag.",
    "By hammer and hand jam.",
    "The age of rain is over.",
    "A new send rises.",
    "Destiny called. It said conditions are good.",
    "Trust the process. Verify the forecast.",
    "Every route is a skill tree.",
    "Unlocking hidden beta since dawn.",
    "Not all who wander are projecting.",
    "The road goes ever on... to the crag.",
    "Your mount is a hatchback.",
    "Beware the false summit.",
    "Chasing sunlight like a solar-powered goblin.",
    "The forecast is mightier than optimism.",
    "Cragwarts School of Grip and Wizardry.",
    "Dungeons, Dragons, and Dynos.",
    "The guild approves this objective.",
    "Certified goblin mode.",
    "Min-maxing the weekend.",
    "Rock and roll initiative.",
    "The chosen one forgot their shoes.",
    "Good conditions are canon.",
    "Reality is temporary. Projects are forever.",
    "Eat chalk. Seek adventure.",
    "World Eaters eat worlds. ChalkEaters eat weekends.",
    "The crag weaves as the crag wills.",
    "There are neither beginnings nor endings to a project.",
    "Journey before parking.",
    "These routes accept chalk.",
    "One route to rule your weekend.",
    "The beacons are lit. The weather is good.",
    "Not all who wander are looking for beta.",
    "A long-expected send.",
    "The road goes ever on... uphill.",
    "Even the smallest climber can change the approach.",
    "Second breakfast at the trailhead.",
    "The age of rain is over.",
    "The deep holds still remember.",
    "A red sun rises. Good friction tonight.",
    "The mountain calls for aid.",
    "There is always another project.",
    "The most important move is the next one.",
    "Strength before weakness. Skin before glory.",
    "Sometimes a route is just a route.",
    "Life before low tide.",
    "Wetness is a wheel.",
    "The pattern demands dry rock.",
    "Time to toss the dice.",
    "Fortune prick me, that's steep.",
    "The wheel turns. Conditions change.",
    "The dragon is reborn. The project remains.",
    "The route marked you long ago.",
    "Better to be stubborn than sensible.",
    "The winds favor today's objective.",
    "This slope has seen many ages.",
    "There is always another secret crag.",
    "Ash fell. The friction improved.",
    "Misty weather, clear beta.",
    "Some projects survive empires.",
    "Certain routes refuse to be forgotten.",
    "Written in metal. Scratched in chalk.",
    "The forecast remembers what men forget.",
    "Storms pass. Projects remain.",
    "Investiture not included.",
    "The rock has its own intent.",
    "For the Emperor's weekend.",
    "Blessed is the dry season.",
    "The crux protects.",
    "Hope is the first step on the approach.",
    "The mountain is pleased.",
    "Cadia fell. This route still stands.",
    "Only in death does the project end.",
    "Purge the rain forecast.",
    "The route requires more faith.",
    "Approved by the Mechanicum of Conditions.",
    "Zug zug to the parking lot.",
    "Work work... then climb.",
    "The forecast is not prepared.",
    "Victory or repair your skin.",
    "Lok'tar overhang.",
    "The mountain grants no epics.",
    "The raid begins at sunrise.",
    "Honor among belayers.",
    "A good day to leave the city.",
    "The route has awakened.",
    "Piton seven locked.",
    "Another world. Another crag.",
    "The gate is open.",
    "Indeed.",
    "Ancient technology predicts dry granite.",
    "Explorers wanted.",
    "Puddle jumpers not included.",
    "The approach is off-world.",
    "Unexpectedly advanced weather magic.",
    "Humanity's greatest achievement: good conditions.",
    "Winter is postponed.",
    "The forecast knows something.",
    "A route has no easy grade.",
    "The north remembers wet sandstone.",
    "Chaos is a ladder. So is this route.",
    "Send and let send.",
    "Fire cannot climb this slab.",
    "The wall is dark and full of projects.",
    "Valar... wrong universe.",
    "Summer is climbing.",
    "The mountain was here before kings.",
    "Ancient things sleep beneath the talus.",
    "A good omen for friction.",
    "Beyond the map lies better rock.",
    "The old paths remain.",
    "Every legend started with a bad approach.",
    "Fortune favors early departures.",
    "The crag abides.",
    "Weather is temporary. Beta is eternal.",
    "Some quests require chalk.",
    "You shall not punt.",
    "Fly, you fools... to the next sector.",
    "The route is not late. It arrives precisely when conditions allow.",
    "The dark lord hates perfect friction.",
    "Witness the strength of small footholds.",
    "The mountain has chosen violence.",
    "A light in the weather forecast.",
    "The send that was promised.",
    "The last alliance of climbers and sunscreen.",
    "Seven days of rain were foretold. Today is not one of them.",
    "The forecast must flow.",
    "Fear is the friction-killer.",
    "The dry rock awakens.",
    "He who controls the weather controls the weekend.",
    "The approach is long, but the forecast is clear.",
    "A storm is coming. Somewhere else.",
    "Blessed be the cloud cover.",
    "The sandstone endures.",
    "The forecast has seen many futures.",
    "Today's path diverges from the rain.",
    "Ash fell. Conditions improved.",
    "The mists conceal many projects.",
    "The Lord Ruler hated humidity.",
    "Some forecasts are written in steel.",
    "There is always another weather window.",
    "The clouds keep their secrets.",
    "Preservation favors dry granite.",
    "Ruin prefers your days off.",
    "A clear sky is a rare metal.",
    "The forecast survived the Catacendre.",
    "The Dor is strong today.",
    "The chasm line points toward good friction.",
    "Rain has been politely declined.",
    "The weather has become unusually cooperative.",
    "Elantris has fallen. The crag is dry.",
    "Ancient symbols predict splitter conditions.",
    "The storm broke before dawn.",
    "The mountains remember the old weather.",
    "Some maps should not be trusted.",
    "This forecast glows faintly with promise.",
    "The Silmarils reflected excellent visibility.",
    "The winds of Manwë are favorable.",
    "No shadow reaches this valley today.",
    "Before the first age, there was good friction.",
    "The eagles report clear skies.",
    "Morgoth definitely brought that rain.",
    "The light still reaches these cliffs.",
    "The west wind carries good news.",
    "Not every dark cloud serves a dark lord.",
    "Starlight and sandstone.",
    "The night is dark, but tomorrow is sunny.",
    "Winter has been delayed.",
    "The forecast remembers.",
    "The north remembers wet sandstone.",
    "The wall is dry and full of projects.",
    "A storm is coming. Check Tuesday.",
    "The sun rises in the east and the friction rises with it.",
    "Valar morghulis. Conditions permitting.",
    "Some forecasts are bastards.",
    "The long summer of sending continues.",
    "Death can wait. The weather cannot.",
    "Zagreus would have climbed this.",
    "Even the underworld predicts sunshine.",
    "Another escape attempt. Another perfect forecast.",
    "The Fates approve today's conditions.",
    "Olympus grants a tailwind.",
    "Chthonic levels of friction.",
    "No gods. Only beta.",
    "The House of Hades recommends sunscreen.",
    "Melinoë predicted this weather.",
    "The guidebook was consumed by corruption.",
    "A blood moon rises. The crag remains open.",
    "You feel an evil presence watching the forecast.",
    "The clouds have been defeated.",
    "Suitable climbing conditions are approaching.",
    "The air feels unusually crisp.",
    "The weather is going through a hardmode phase.",
    "Slime rain not detected.",
    "A solar eclipse would ruin everything.",
    "The dry season has awoken.",
    "The weather weaves as the weather wills.",
    "There are no beginnings or endings to dry spells.",
    "The Pattern favors this objective.",
    "The Wheel turns. The rock dries.",
    "A wind from the Mountains of Mist.",
    "Fortune prick me, that's good friction.",
    "The storm has been gentled.",
    "The forecast rides on the winds of time.",
    "Clouds gather beyond the horizon.",
    "The Pattern is surprisingly climbable.",
    "The beacons are lit. The crag calls for aid.",
    "The rain passed into the west.",
    "A long-expected weather window.",
    "There and back again before sunset.",
    "Even darkness cannot hide perfect friction.",
    "The mountain is never late.",
    "One forecast to rule the weekend.",
    "The road goes ever on toward dry rock.",
    "The clouds are thin and full of hope.",
    "The sun breaks through at first light.",
    "The Emperor protects. The forecast helps.",
    "Hope is the first step toward good conditions.",
    "The machine spirit approves this pressure system.",
    "Exterminatus canceled due to sunshine.",
    "Cadia fell. The high pressure remained.",
    "Blessed is the dry season.",
    "The mountain has survived worse forecasts.",
    "The crux protects.",
    "Chaos brought rain. Order restored sunshine.",
    "The Golden Path leads to perfect friction."
];

const randomPhrase =
    phrases[Math.floor(Math.random() * phrases.length)];

document.getElementById("message").textContent = randomPhrase;